name:                fpinhaskell
version:             0.1.0.0
github:              "tdelev/fpinhaskell"
license:             BSD3
author:              "Tomche"
maintainer:          "tomce.delev@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            playing

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/tdelev/fpinhaskell#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  fpinhaskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fpinhaskell

tests:
  fpinhaskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fpinhaskell
